global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  # - job_name: 'eureka-service'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['eureka-server:8761']
  #       labels:
  #         application: 'eureka-server'

  # - job_name: 'api-gateway'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['api-gateway:8181']
  #       labels:
  #         application: 'api-gateway'

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8080']
        labels:
          application: 'order-service'
  
  - job_name: 'restaurant-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['restaurant-service:8080']
        labels:
          application: 'restaurant-service'

  - job_name: 'delivery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['delivery-service:8080']
        labels:
          application: 'delivery-service'
